name: nsoliquid
version: 0.1.0
description: An unofficial discord bot for nsopiba
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  nyxx: ^6.2.1
  nyxx_commands: ^6.0.2
  nyxx_interactions: ^4.6.0
  ini: ^2.1.0
  yaml: ^3.1.2
  toml: ^0.15.0
